name: Build and Upload
on:
  push:
    branches:
      - snomed-master
      - 'snomed-release-*'
      - form-issue-temp
    tags:
      - 'snomed-[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Docker - Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: package/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bahmni/clinic-config:snomed-${{ github.run_number }},bahmni/clinic-config:snomed-latest
